all:
  hosts:
    openshift-4-dev:
      ansible_connection: local
      ansible_host: localhost
      ansible_python_interpreter: "{{ phdisble_suitcase_dir }}/bin/python3"
      openshift_namespace: svc1394d-phd-assess
  vars:
    phd-assess:
      is_test: 'true'

    ### Secrets
    keybase_secrets_folder: "/keybase/team/epfl_phdassess/dev/"

    ### Zeebe
    zeebe_version: '8.3.3'
    zeebe_camunda_image_path: "camunda/zeebe"
    zeebe_camunda_image_full_path_on_quay:
      "{{ quay_host }}/{{ quay_organisation_name }}/{{ zeebe_camunda_image_path }}"
