all:
  hosts:
    openshift-4-test:
      ansible_connection: local
      ansible_host: localhost
      ansible_python_interpreter: "{{ phdisble_suitcase_dir }}/bin/python3"
      openshift_namespace: svc1394t-phd-assess
  vars:
    # Secrets
    keybase_secrets_folder: "/keybase/team/epfl_phdassess/test/"

    # Zeebe
    ## Camunda Image config
    zeebe_version:
      # '8.3.3'
      # '8.3.20'
      # '8.4.18'
      '8.5.17'
    zeebe_repository:
      "docker.io"
    zeebe_camunda_image_path:
      "{{ zeebe_repository }}/camunda/zeebe"
    zeebe_camunda_image_full_path:
      "{{ zeebe_camunda_image_path }}:{{ zeebe_version }}"

    ## Quay Image destination config
    zeebe_quay_image_name:
      "camunda/zeebe"
    zeebe_quay_image_path:
      "{{ quay_repo }}/{{ zeebe_quay_image_name }}"
    zeebe_quay_image_full_path:
      "{{ zeebe_quay_image_path }}:{{ zeebe_version }}"

    ## Backup / Restore S3
    zeebe_backup_s3_bucket_name_file:
      "{{keybase_secrets_folder }}S3-zeebe-backup/BUCKETNAME"
    zeebe_backup_s3_access_key_file:
      "{{keybase_secrets_folder }}S3-zeebe-backup/ACCESSKEY"
    zeebe_backup_s3_secret_key_file:
      "{{keybase_secrets_folder }}S3-zeebe-backup/SECRETKEY"

    # Meteor
    node_for_meteor_image_name: 'ubuntu-node-14'
    web_app_image_name: 'meteor-web-app'
    web_app_image_tag: 'latest'

    web_app_nip_io_url: "phd-assess-test.10.98.42.205.nip.io"
    #web_app_url: "phd-annual-report-test.epfl.ch"
    web_app_full_url: "https://{{ web_app_nip_io_url }}"

    web_app_mongo_url: "mongodb://web-app-db:27017/meteor"

    web_app_zeebe_log_level: "ERROR"
    web_app_debug_env: "phd-assess:*"
    web_app_node_env: "development"
    web_app_node_options: "--max_old_space_size=1536"
    web_app_db_image: "{{ quay_repo }}/{{ db_image_name }}:{{ db_image_tag }}"

    web_app_secret_mongo_persistent_db: true

    web_app_meteor_settings:
      public:
        isTest:
          "true"
        phdAssessRoleAdmin:
          "PhD-annual-report-admin"
        phdAssessRoleProgramAssistant:
          "PhD-annual-report-administrative-assistant"

    db_image_name: "mongo"
    db_image_tag: "6"

    ## Security
    web_app_tequila_allowed_request_hosts: "10.180.21.0/24"

    # Route
    avi_route_access_level: private

    # Microservices
    microservice_node_base_tag: "18-alpine"

    ## Notifier
    notifier_send_real_email: false
    notifier_from_address: "Annual report test <noreply@epfl.ch>"

    ## GED
    alfresco_url: "https://integration-gedetu.epfl.ch"
    alfresco_ignore_TLS_error: true
    alfresco_username: "{{ lookup('file', '/keybase/team/epfl_phdassess/ALFRESCO_USERNAME') }}"
    alfresco_password: "{{ lookup('file', '/keybase/team/epfl_phdassess/ALFRESCO_PASSWORD') }}"

    ## ISA
    isa_url: "{{ lookup('file', keybase_secrets_folder + 'ISA_POST_STUDENT_RESULT_URL') }}"

    # Monitoring
    grafana_dashboard_instance: grafana-test
