# Setup quay to have the necessary base images
- name: Images - Pull Zeebe image
  community.docker.docker_image:
    repository: "{{ zeebe_repository }}"
    name: "{{ zeebe_camunda_image_path }}"
    tag: "{{ zeebe_version }}"
    source: pull

- name: Images - Tag and push Zeebe to Quay
  community.docker.docker_image:
    name: "{{ zeebe_camunda_image_full_path }}"
    repository: "{{ zeebe_quay_image_path }}"
    tag: "{{ zeebe_version }}"
    push: true
    source: local

- name: Images - Pull Ubuntu Focal image
  community.docker.docker_image:
    name: "ubuntu"
    tag: "focal"
    source: pull

- name: Images - Tag and push Ubuntu Focal to Quay
  community.docker.docker_image:
    name: "ubuntu"
    repository: "{{ quay_repo }}/ubuntu"
    tag: "focal"
    push: true
    source: local

- name: Images - Pull the Node 18 for microservices as base image
  community.docker.docker_image:
    name: "node"
    tag: "{{ microservice_node_18_base_tag }}"
    source: pull

- name: Images - Tag and push Node 18
  community.docker.docker_image:
    name: "node"
    repository: "{{ quay_repo }}/node"
    tag: "{{ microservice_node_18_base_tag }}"
    push: true
    source: local

- name: Images - Pull the Node 22 for microservices as base image
  community.docker.docker_image:
    name: "node"
    tag: "{{ microservice_node_22_base_tag }}"
    source: pull

- name: Images - Tag and push Node 22
  community.docker.docker_image:
    name: "node"
    repository: "{{ quay_repo }}/node"
    tag: "{{ microservice_node_22_base_tag }}"
    push: true
    source: local

- name: Images - Pull the Node 24 for microservices as base image
  community.docker.docker_image:
    name: "node"
    tag: "{{ microservice_node_24_base_tag }}"
    source: pull

- name: Images - Tag and push Node 24
  community.docker.docker_image:
    name: "node"
    repository: "{{ quay_repo }}/node"
    tag: "{{ microservice_node_24_base_tag }}"
    push: true
    source: local

- name: Images - Pull the MongoDB for web-app
  community.docker.docker_image:
    name: "{{ db_image_name }}"
    tag: "{{ db_image_tag }}"
    source: pull

- name: Images - Tag and push the MongoDB
  community.docker.docker_image:
    name: "{{ db_image_name }}"
    repository: "{{ quay_repo }}/{{ db_image_name }}"
    tag: "{{ db_image_tag }}"
    push: true
    source: local
