# Setup quay to have the necessary base images
- name: Images - Pull Zeebe image
  community.docker.docker_image:
    name: "{{ zeebe_camunda_image_path }}"
    tag: "{{ zeebe_version }}"
    source: pull

- name: Images - Tag and push Zeebe to Quay
  community.docker.docker_image:
    name: "{{ zeebe_camunda_image_path }}"
    repository: "{{ zeebe_camunda_image_full_path_on_quay }}"
    tag: "{{ zeebe_version }}"
    push: true
    source: local
