- name: Web app Deployment
  kubernetes.core.k8s:
    definition:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: "web-app"
        namespace: "{{ openshift_namespace }}"
        labels:
          app.kubernetes.io/name: "web-app"
          app.kubernetes.io/component: "frontend"
          app.kubernetes.io/part-of: "web"
          deployment.name: "web-app"
        annotations:
          app.openshift.io/vcs-uri: "https://github.com/epfl-si/PhDAssess"
          app.openshift.io/connects-to: '["web-app-db", "zeebe-0"]'
      spec:
        replicas: 1
        selector:
          matchLabels:
            deployment.name: "web-app"
        template:
          metadata:
            labels:
              deployment.name: "web-app"
              app.kubernetes.io/instance: "web-app"
          spec:
            serviceAccountName: "{{ quay_service_account_name }}"
            containers:
              - name: "web-app"
                image: "{{ quay_repo }}/{{ web_app_image_name }}:{{ web_app_image_tag }}"
                command:
                  - node
                  - main.js
                ports:
                  - name: meteor
                    containerPort: 3000
                resources:
                  requests:
                    cpu: "50m"
                    memory: "800Mi"
                  limits:
                    memory: "4Gi"
                readinessProbe:
                  httpGet:
                    path: /metrics
                    port: 3000
                  initialDelaySeconds: 15
                  periodSeconds: 3
                  failureThreshold: 120
                envFrom:
                  - secretRef:
                      name: "all"
                  - secretRef:
                      name: "{{ meteor_secrets_name }}"
                  - secretRef:
                      name: "microservice.ged"
                env:
                  - name: "PORT"
                    value: "3000"
                  - name: "ROOT_URL"
                    value: "{{ web_app_full_url }}"
                  - name: "MONGO_URL"
                    value: "{{ web_app_mongo_url }}"
                  - name: "ZEEBE_ADDRESS"
                    value: "{{ zeebe_gateway_service_name }}:{{ zeebe_gateway_network_port }}"
                  - name: "ZEEBE_NODE_LOG_LEVEL"
                    value: "{{ web_app_zeebe_log_level }}"
                  - name: "DEBUG"
                    value: "{{ web_app_debug_env }}"
                  - name: "METEOR_SETTINGS"
                    value: "{{ web_app_meteor_settings | to_json }}"
                  - name: "ISA_IMPORT_API_URL"
                    value: "http://isa.epfl.ch/services/v1/doctorants/current/programme"
                  - name: "ZEEBE_WORKER_TIMEOUT"
                    value: "300000"
                  - name: "ZEEBE_WORKER_MAX_JOBS_TO_ACTIVATE"
                    # tried:
                    #   - 100: too much, 10 were gone as error
                    #   - 66: too much, 3 were gone as error
                    value: "50"
                  - name: "TZ"
                    value: "Europe/Zurich"
                  - name: "NODE_ENV"
                    value: "{{ web_app_node_env }}"
                  - name: "NODE_OPTIONS"
                    value: "{{ web_app_node_options }}"
                  - name: "TEQUILA_ALLOWED_REQUEST_HOSTS"
                    value: "{{ web_app_tequila_allowed_request_hosts }}"
                  - name: "ALFRESCO_URL"
                    value: "{{ alfresco_url }}"
                  - name: "NODE_TLS_REJECT_UNAUTHORIZED"
                    value: "{{ 0 if alfresco_ignore_TLS_error is defined and alfresco_ignore_TLS_error == true }}"
