- name: Mongo Deployment
  kubernetes.core.k8s:
    definition:
      apiVersion: apps/v1
      kind: StatefulSet
      metadata:
        name: "web-app-db"
        namespace: "{{ openshift_namespace }}"
        labels:
          app.kubernetes.io/name: "web-app-db"
          app.kubernetes.io/component: "database"
          app.kubernetes.io/part-of: "web"
          deployment.name: "web-app-db"
      spec:
        replicas: 1
        selector:
          matchLabels:
            deployment.name: "web-app-db"
        template:
          metadata:
            labels:
              app.kubernetes.io/instance: "{{ db_image_name }}"
              app.kubernetes.io/version: "{{ db_image_tag }}"
              deployment.name: "web-app-db"
          spec:
            serviceAccountName: "{{ quay_service_account_name }}"
            containers:
              - name: "web-app-db"
                image: "{{ web_app_db_image }}"
                imagePullPolicy: Always
                resources:
                  requests:
                    cpu: "10m"
                    memory: "400Mi"
                  limits:
                    memory: "1Gi"
                volumeMounts:
                  - name: data-db
                    mountPath: /data/db
            volumes:
              - name: data-db
                emptyDir: {}

- name: MongoDB Service
  kubernetes.core.k8s:
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: "web-app-db"
        namespace: "{{ openshift_namespace }}"
      spec:
        type: ClusterIP
        ports:
          - name: "web-app-db"
            port: 27017
            targetPort: 27017
        selector:
          deployment.name: "web-app-db"
