- name: Web app secrets
  ansible.builtin.include_tasks:
    file: web-app/secrets.yml
    apply:
      tags:
        - web-app
        - web-app.secrets
  tags:
    - web-app
    - web-app.secrets

- name: Web app Mongo DB
  ansible.builtin.include_tasks:
    file: web-app/db.yml
    apply:
      tags:
        - web-app
        - web-app.db
  tags:
    - web-app
    - web-app.db

- name: Web app Meteor
  ansible.builtin.include_tasks:
    file: web-app/app.yml
    apply:
      tags:
        - web-app
        - web-app.meteor
  tags:
    - web-app
    - web-app.meteor

- name: Web app services
  ansible.builtin.include_tasks:
    file: web-app/services.yml
    apply:
      tags:
        - web-app
        - web-app.services
  tags:
    - web-app
    - web-app.services

- name: Web app route
  ansible.builtin.include_tasks:
    file: web-app/route.yml
    apply:
      tags:
        - web-app
        - web-app.route
  tags:
    - web-app
    - web-app.route

- name: Web app monitoring
  ansible.builtin.include_tasks:
    file: web-app/monitoring.yml
    apply:
      tags:
        - web-app
        - web-app.monitoring
  tags:
    - web-app
    - web-app.monitoring
