- name: Applying Meteor App secrets...
  ansible.builtin.include_tasks:
    file: web-app/app.yml
    apply:
      tags:
        - web-app
        - web-app.secrets
  tags:
    - web-app
    - web-app.secrets

- name: Applying Mongo for the Meteor App...
  ansible.builtin.include_tasks:
    file: web-app/db.yml
    apply:
      tags:
        - web-app
        - web-app.db
  tags:
    - web-app
    - web-app.db

- name: Applying Meteor App...
  ansible.builtin.include_tasks:
    file: web-app/app.yml
    apply:
      tags:
        - web-app
        - web-app.meteor
  tags:
    - web-app
    - web-app.meteor

- name: Applying App services...
  ansible.builtin.include_tasks:
    file: web-app/services.yml
    apply:
      tags:
        - web-app
        - web-app.services
  tags:
    - web-app
    - web-app.services
