- name: Web app metrics reader
  kubernetes.core.k8s:
    definition:
      apiVersion: monitoring.coreos.com/v1
      kind: ServiceMonitor
      metadata:
        name: web-app-monitoring
        namespace: '{{ openshift_namespace }}'
      spec:
        endpoints:
          - interval: 15s
            targetPort: 3000
            path: /metrics
        selector:
          matchLabels:
            app.kubernetes.io/name: "web-app-service"

- name: Grafana base folder
  ansible.builtin.include_tasks:
    file: grafana.yml

- name: Web app Grafana dashboard definition
  kubernetes.core.k8s:
    definition:
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: 'web-app-grafana-dashboard'
        namespace: '{{ openshift_namespace }}'
      data:
        json: >
          {{ lookup('file', 'templates/grafana-dashboards/web-app-meteor.json') | string }}

- name: Web app dashboard in Grafana
  kubernetes.core.k8s:
    definition:
      apiVersion: grafana.integreatly.org/v1beta1
      kind: GrafanaDashboard
      metadata:
        name: 'web-app'
        namespace: '{{ openshift_namespace }}'
      spec:
        resyncPeriod: 30s
        allowCrossNamespaceImport: true
        instanceSelector:
          matchLabels:
            dashboards: '{{ grafana_dashboard_instance }}'
        folder: "{{ grafana_folder_name }}"
        configMapRef:
          key: json
          name: 'web-app-grafana-dashboard'

- name: Logs Grafana dashboard definition ConfigMap
  kubernetes.core.k8s:
    definition:
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: 'logs-grafana-dashboard'
        namespace: '{{ openshift_namespace }}'
      data:
        json: >
          {{ lookup('template', 'templates/grafana-dashboards/logs.json') }}

- name: Logs dashboard in Grafana
  kubernetes.core.k8s:
    definition:
      apiVersion: grafana.integreatly.org/v1beta1
      kind: GrafanaDashboard
      metadata:
        name: 'logs'
        namespace: '{{ openshift_namespace }}'
      spec:
        resyncPeriod: 30s
        allowCrossNamespaceImport: true
        instanceSelector:
          matchLabels:
            dashboards: '{{ grafana_dashboard_instance }}'
        folder: "{{ grafana_folder_name }}"
        configMapRef:
          key: json
          name: 'logs-grafana-dashboard'
