- name: Web app Service
  kubernetes.core.k8s:
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: "web-app"
        namespace: "{{ openshift_namespace }}"
        labels:
          app.kubernetes.io/name: "web-app-service"
      spec:
        type: ClusterIP
        ports:
          - name: "http-web"
            port: 80
            protocol: TCP
            targetPort: 3000
        selector:
          deployment.name: "web-app"
