- name: Setting the microservices as Zeebe Clients
  ansible.builtin.include_tasks: _microservice.yml
  loop:
    - name: "notifier"
      git_url: "https://github.com/epfl-si/PhDAssess-Notifier"
      additional_env:
        - ZEEBE_TASK_TYPE: "notification"
          NOTIFIER_PORT: "{{ notifier_port }}"
          NOTIFIER_HOST: "{{ notifier_host }}"
          NOTIFIER_FROM_ADDRESS: "{{ notifier_from_address }}"
    - name: "pdf"
      git_url: "https://github.com/epfl-si/PhDAssess-PDF"
      additional_env:
        - ZEEBE_TASK_TYPE: "phdBuildPDF"
    - name: "ged"
      git_url: "https://github.com/epfl-si/PhDAssess-GED"
      git_branch: "master"
      additional_env:
        - ZEEBE_TASK_TYPE: "phdGEDDeposit"
          ALFRESCO_URL: "{{ alfresco_url }}"
          NODE_TLS_REJECT_UNAUTHORIZED: "{{ 0 if alfresco_ignore_TLS_error  }}"
      additional_secrets:
        ALFRESCO_USERNAME: "{{ alfresco_username }}"
        ALFRESCO_PASSWORD: "{{ alfresco_password }}"
    - name: "isa"
      node_version: "22-alpine"
      git_url: "https://github.com/epfl-si/PhDAssess-ISA"
      additional_env:
        - ZEEBE_TASK_TYPE: "phdISAPostStudentResult"
      additional_secrets:
        ISA_URL: "{{ isa_url }}"
