- name: Microservices (Zeebe clients)
  ansible.builtin.include_tasks: _microservice.yml
  loop:
    - name: "notifier"
      image_tag: "{{ notifier_image_tag }}"
      node_version: "{{ microservice_node_image_base_tag }}"
      git_url: "https://github.com/epfl-si/PhDAssess-Notifier"
      additional_env:
        - ZEEBE_TASK_TYPE: "notification"
          ALFRESCO_URL: "{{ alfresco_url }}"
          NOTIFIER_PORT: "{{ notifier_port }}"
          NOTIFIER_HOST: "{{ notifier_host }}"
          NOTIFIER_FROM_ADDRESS: "{{ notifier_from_address }}"
      additional_secrets:
        ALFRESCO_USERNAME: "{{ alfresco_username }}"
        ALFRESCO_PASSWORD: "{{ alfresco_password }}"
    - name: "pdf"
      image_tag: "{{ pdf_image_tag }}"
      node_version: "{{ microservice_node_image_base_tag }}"
      git_url: "https://github.com/epfl-si/PhDAssess-PDF"
      additional_env:
        - ZEEBE_TASK_TYPE: "phdBuildPDF"
          NODE_TLS_REJECT_UNAUTHORIZED:
            "{{ 0 if alfresco_ignore_TLS_error is defined and alfresco_ignore_TLS_error == true }}"
    - name: "ged"
      image_tag: "{{ ged_image_tag }}"
      node_version: "{{ microservice_node_image_base_tag }}"
      git_url: "https://github.com/epfl-si/PhDAssess-GED"
      additional_env:
        - ZEEBE_TASK_TYPE: "phdGEDDeposit"
          ALFRESCO_URL: "{{ alfresco_url }}"
          NODE_TLS_REJECT_UNAUTHORIZED:
            "{{ 0 if alfresco_ignore_TLS_error is defined and alfresco_ignore_TLS_error == true }}"
      additional_secrets:
        ALFRESCO_USERNAME: "{{ alfresco_username }}"
        ALFRESCO_PASSWORD: "{{ alfresco_password }}"
    - name: "isa"
      image_tag: "{{ isa_image_tag }}"
      node_version: "{{ microservice_node_image_base_tag }}"
      git_url: "https://github.com/epfl-si/PhDAssess-ISA"
      additional_env:
        - ZEEBE_TASK_TYPE: "phdISAPostStudentResult"
      additional_secrets:
        ISA_URL: "{{ isa_url }}"
