{
 "title": "Zeebe DB monitor",
 "description": "Custom made reader for the Zeebe RocksDB files",
 "tags": [
  "db",
  "rocksdb"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Column families", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Column families scrape duration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "rate(zeebe_db_column_families_keys_read_duration_seconds_sum[5m]) / rate(zeebe_db_column_families_keys_read_duration_seconds_count[5m])"
    }
   ]
  },
  {
   "title": "Column families",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    { "expr": "zeebe_db_column_family_entries", "legendFormat": "{{column_family}}" }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "zeebe_db_column_family_entries{column_family=\"JOBS\"}",
     "legendFormat": "{{column_family}}"
    }
   ]
  },
  { "title": "Incidents", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Errors",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "zeebe_db_column_family_incident_entries",
     "legendFormat": "{{error_message}}"
    }
   ]
  },
  {
   "title": "Errors evolution",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "sum by (error_message) (zeebe_db_column_family_incident_entries)",
     "legendFormat": "{{error_message}}"
    }
   ]
  }
 ]
}