- name: BuildConfig for the custom Zeebe image
  kubernetes.core.k8s:
    definition:
      apiVersion: build.openshift.io/v1
      kind: BuildConfig
      metadata:
        name: zeebe-image
        namespace: "{{ openshift_namespace }}"
      spec:
        source:
          type: Git
          git:
            ref: "main"
            uri: "https://github.com/epfl-si/PhDAssess"
        strategy:
          type: Docker
          dockerStrategy:
            pullSecret:
              name: quay-pull-push-secret
            buildArgs:
              - name: "BASE_IMAGE"
                value: "{{ zeebe_camunda_image_path }}:{{ zeebe_version }}"
            dockerfilePath: "docker/zeebe/Dockerfile"
        output:
          to:
            kind: DockerImage
            name: "{{ zeebe_quay_image_path }}:{{ zeebe_version }}"
          pushSecret:
            name: quay-pull-push-secret
        resources:
          requests:
            cpu: "10m"
            memory: "1Gi"
          limits:
            memory: "1Gi"

- name: BuildConfig for the Zeebe backuper tool
  kubernetes.core.k8s:
    definition:
      apiVersion: build.openshift.io/v1
      kind: BuildConfig
      metadata:
        name: zeebe-backuper-image
        namespace: "{{ openshift_namespace }}"
      spec:
        source:
          type: Git
          git:
            uri: "https://github.com/epfl-si/PhDAssess.ops"
            ref: "main"
          contextDir: zeebe-backuper
        strategy:
          type: Docker
          dockerStrategy:
            pullSecret:
              name: quay-pull-push-secret
            buildArgs:
              - name: "BASE_IMAGE"
                value: "{{ quay_repo }}/node:22-alpine"
        output:
          to:
            kind: DockerImage
            name: "{{ quay_repo }}/zeebe-backuper:latest"
          pushSecret:
            name: quay-pull-push-secret
        resources:
          requests:
            cpu: "10m"
            memory: "1Gi"
          limits:
            memory: "1Gi"

- name: BuildConfig for the Meteor App
  kubernetes.core.k8s:
    definition:
      apiVersion: build.openshift.io/v1
      kind: BuildConfig
      metadata:
        name: "{{ web_app_image_name }}"
        namespace: "{{ openshift_namespace }}"
      spec:
        source:
          type: Git
          git:
            ref: "{{ web_app_repository_tag | default('main') }}"
            uri: "https://github.com/epfl-si/PhDAssess"
        strategy:
          type: Docker
          dockerStrategy:
            pullSecret:
              name: quay-pull-push-secret
            buildArgs:
              - name: "BASE_IMAGE"
                value: "{{ quay_repo }}/{{ node_for_meteor_image_name }}"
        output:
          to:
            kind: DockerImage
            name: "{{ quay_repo }}/{{ web_app_image_name }}:{{ web_app_image_tag }}"
          pushSecret:
            name: quay-pull-push-secret
        resources:
          requests:
            cpu: "10m"
            memory: "4Gi"
          limits:
            memory: "4Gi"

- name: BuildConfig for the disk usage monitor
  kubernetes.core.k8s:
    definition:
      apiVersion: build.openshift.io/v1
      kind: BuildConfig
      metadata:
        name: "disk-usage-exporter"
        namespace: "{{ openshift_namespace }}"
      spec:
        source:
          type: Git
          git:
            ref: "master"
            uri: "https://github.com/epfl-si/PhDAssess"
          contextDir: "docker/monitoring"
        strategy:
          type: Docker
          dockerStrategy:
            pullSecret:
              name: quay-pull-push-secret
            buildArgs:
              - name: "BASE_IMAGE"
                value: "{{ quay_repo }}/node:22-alpine"
        output:
          to:
            kind: DockerImage
            name: "{{ monitoring_node_disk_usage_exporter_image }}:latest"
          pushSecret:
            name: quay-pull-push-secret
        resources:
          requests:
            cpu: "10m"
            memory: "1Gi"
          limits:
            memory: "1Gi"

- name: BuildConfig for the zeebe db monitor
  kubernetes.core.k8s:
    definition:
      apiVersion: build.openshift.io/v1
      kind: BuildConfig
      metadata:
        name: "zeebe-db-monitor"
        namespace: "{{ openshift_namespace }}"
      spec:
        source:
          type: Git
          git:
            uri: "https://github.com/epfl-si/zeebe-db-monitor"
        strategy:
          type: Docker
          dockerStrategy:
            pullSecret:
              name: quay-pull-push-secret
            buildArgs:
              - name: "BASE_IMAGE"
                value: "{{ quay_repo }}/node:24-alpine"
        output:
          to:
            kind: DockerImage
            name: "{{ zeebe_db_monitor_image }}:latest"
          pushSecret:
            name: quay-pull-push-secret
        resources:
          requests:
            cpu: "10m"
            memory: "1Gi"
          limits:
            memory: "1Gi"
