- name: Service account for Quay
  ansible.builtin.include_tasks:
    file: quay/serviceAccounts.yml
    apply:
      tags:
        - serviceAccounts
        - quay
        - images
        - buildConfigs
  tags:
    - serviceAccounts
    - quay
    - images
    - buildConfigs
    - zeebe
    - zeebe.quorum
    - microservices
    - web-app
    - web-app.db
    - web-app.meteor

- name: "[On localhost] Doing Quay images upload..."
  ansible.builtin.include_tasks:
    file: quay/images.yml
    apply:
      tags:
        - quay
        - images
        - never
  tags:
    - quay
    - images
    - never

- name: Secrets
  ansible.builtin.include_tasks:
    file: secrets.yml
    apply:
      tags: secrets
  tags: secrets

- name: BuildConfigs
  when: >-
    openshift_environnement in ["development", "test"]
  ansible.builtin.include_tasks:
    file: buildConfigs.yml
    apply:
      tags:
        - buildConfigs
  tags:
    - buildConfigs

- name: Zeebe stack
  ansible.builtin.include_tasks:
    file: zeebe/main.yml
  tags:
    - zeebe
    - zeebe.configMaps
    - zeebe.secrets
    - zeebe.exporter
    - zeebe.exporter.tear-down
    - zeebe.exporter.destroy-es-data
    - zeebe.quorum
    - zeebe.service
    - zeebe.monitoring
    - zeebe.cronJobs

- name: Notifier microservice
  ansible.builtin.include_tasks:
    file: microservices/main.yml
    apply:
      tags:
        - microservices
  tags:
    - microservices

- name: Web App
  ansible.builtin.include_tasks:
    file: web-app/main.yml
  tags:
    - web-app
    - web-app.secrets
    - web-app.db
    - web-app.meteor
    - web-app.services
    - web-app.route
    - web-app.monitoring

- name: Network policies
  ansible.builtin.include_tasks:
    file: networkPolicies.yml
    apply:
      tags: network-policies
  tags: network-policies

- name: Routes
  ansible.builtin.include_tasks:
    file: routes.yml
    apply:
      tags:
        - routes
  tags:
    - routes

- name: Alerts
  ansible.builtin.include_tasks:
    file: alerts.yml
    apply:
      tags: alerts
  tags: alerts
