- name: Service account for Quay
  ansible.builtin.include_tasks:
    file: quay/serviceAccounts.yml
    apply:
      tags:
        - always
        - quay
        - serviceAccounts
  tags:
    - always
    - quay
    - serviceAccounts

- name: "[On localhost] Doing Quay images upload..."
  ansible.builtin.include_tasks:
    file: quay/images.yml
    apply:
      tags:
        - quay
        - never
  tags:
    - quay
    - never

- name: Secrets
  ansible.builtin.include_tasks:
    file: secrets.yml
    apply:
      tags: secrets
  tags: secrets

- name: BuildConfigs
  when: >-
    openshift_namespace in ["svc1394d-phd-assess"]
  ansible.builtin.include_tasks:
    file: buildConfigs.yml
    apply:
      tags:
        - buildConfigs
  tags:
    - buildConfigs

- name: Zeebe stack
  ansible.builtin.include_tasks:
    file: zeebe/main.yml
  tags:
    - zeebe
    - zeebe.configMaps
    - zeebe.secrets
    - zeebe.quorum
    - zeebe.service
    - zeebe.monitoring

- name: Notifier microservice
  ansible.builtin.include_tasks:
    file: microservices/main.yml
    apply:
      tags:
        - microservices
  tags:
    - microservices

- name: Web App
  ansible.builtin.include_tasks:
    file: web-app/main.yml
  tags:
    - web-app
    - web-app.secrets
    - web-app.db
    - web-app.meteor
    - web-app.services
    - web-app.route
    - web-app.monitoring

- name: Network policies
  ansible.builtin.include_tasks:
    file: networkPolicies.yml
    apply:
      tags: network-policies
  tags: network-policies

- name: Post process suggestions
  vars:
    post_process_message: |
      Now you can:
        - Check the Zeebe stack status with zbctl
          - oc port-forward pod/zeebe-0-0 26501:26500
          - watch zbctl status --insecure --port 26501
  ansible.builtin.debug:
    msg: "{{ post_process_message.split('\n') }}"
  tags:
    - zeebe
