- name: Secrets for all
  kubernetes.core.k8s:
    definition:
      apiVersion: v1
      kind: Secret
      type: Opaque
      metadata:
        name: "{{ default_secrets_name }}"
        namespace: "{{ openshift_namespace }}"
      stringData:
        PHDASSESS_ENCRYPTION_KEY:
          "{{
            lookup('file', keybase_secrets_folder + 'PHDASSESS_ENCRYPTION_KEY')
           }}"
