- name: Secrets
  kubernetes.core.k8s:
    definition:
      apiVersion: v1
      kind: Secret
      type: Opaque
      metadata:
        name: "{{ default_secrets_name }}"
        namespace: "{{ openshift_namespace }}"
      stringData:
        PHDASSESS_ENCRYPTION_KEY: >
          "{{
            lookup('file', keybase_secrets_folder + 'PHDASSESS_ENCRYPTION_KEY')
           }}"

- name: Meteor app secrets
  kubernetes.core.k8s:
    definition:
      apiVersion: v1
      kind: Secret
      type: Opaque
      metadata:
        name: "{{ meteor_secrets_name }}"
        namespace: "{{ openshift_namespace }}"
      stringData:
        API_EPFL_CH_TOKEN: >
          "{{
            lookup('file', '/keybase/team/epfl_phdassess/API_EPFL_CH_TOKEN')
          }}"
        MONGO_PERSISTENT_URL: >
          "{{
            lookup('file', keybase_secrets_folder + 'MONGO_PERSISTENT_URL')
          }}"
