# inspired from https://github.com/camunda-community-hub/zeebe-docker-compose.git

services:
  zeebe_node_0:
    profiles: [zeebe, monitoring]
    extends:
      file: template-zeebe-compose.yml
      service: zeebe_node_0
    container_name: zeebe
    environment:
      - ZEEBE_BROKER_CLUSTER_NODEID=0
    volumes:
      - ./volumes/zeebe_data_node_0:/usr/local/zeebe/data
      #- ./volumes/new_zeebe_data_node_0:/usr/local/zeebe/data
    ports:
      - "29501-29503:26500-26502"
      - "19600:9600"
    depends_on:
      elasticsearch:
        condition: service_healthy

  zeebe_node_1:
    profiles: [zeebe, monitoring]
    extends:
      file: template-zeebe-compose.yml
      service: zeebe_node_1
    container_name: zeebe_1
    environment:
      - ZEEBE_BROKER_CLUSTER_NODEID=1
    volumes:
      - ./volumes/zeebe_data_node_1:/usr/local/zeebe/data
      #- ./volumes/new_zeebe_data_node_1:/usr/local/zeebe/data
    ports:
      - "29504-29506:26500-26502"
      - "19601:9600"

  zeebe_node_2:
    profiles: [zeebe, monitoring]
    extends:
      file: template-zeebe-compose.yml
      service: zeebe_node_2
    container_name: zeebe2
    environment:
      - ZEEBE_BROKER_CLUSTER_NODEID=2
    volumes:
      - ./volumes/zeebe_data_node_2:/usr/local/zeebe/data
      #- ./volumes/new_zeebe_data_node_2:/usr/local/zeebe/data
    ports:
      - "29507-29509:26500-26502"
      - "19602:9600"

  elasticsearch:
    profiles: [zeebe, monitoring]
    image: elasticsearch:8.12.2
    container_name: elasticsearch
    environment:
      - network.host=0.0.0.0
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
      - xpack.security.transport.ssl.enabled=false
      - transport.port=9300
      - transport.host=0.0.0.0
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200/_cluster/health?wait_for_status=yellow&timeout=5s"]
      interval: 10s
      retries: 15
      start_period: 30s

  kibana:
    profiles: [monitoring]
    image: kibana:8.12.2
    container_name: kibana
    depends_on:
      elasticsearch:
        condition: service_healthy
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - SERVER_NAME=kibana
      - SERVER_HOST=0.0.0.0

  operate:
    profiles: [monitoring]
    container_name: operate
    image: camunda/operate:8.5.21
    depends_on:
      elasticsearch:
        condition: service_healthy
      zeebe_node_0:
        condition: service_healthy
    ports:
      - "8082:8080"
    environment:
      - CAMUNDA_OPERATE_ZEEBE_GATEWAYADDRESS=zeebe:26500  # keep it that way or enjoy the ride on the name configs
      - camunda.operate.elasticsearch.url=http://elasticsearch:9200
      - camunda.operate.zeebeelasticsearch.url=http://elasticsearch:9200

  notifier:
    profiles: [microservices]
    build:
      context: ../../PhDAssess-Notifier
    environment:
      - ZEEBE_ADDRESS=zeebe_node_0:29501
    env_file:
      - ../../PhDAssess-Notifier/.env

  pdf:
    profiles: [microservices]
    build:
      context: ../../PhDAssess-PDF
    environment:
      - ZEEBE_ADDRESS=zeebe_node_0:29501
    env_file:
      - ../../PhDAssess-PDF/.env

  ged:
    profiles: [microservices]
    build:
      context: ../../PhDAssess-GED
    environment:
      - ZEEBE_ADDRESS=zeebe_node_0:29501
    env_file:
      - ../../PhDAssess-GED/.env

  isa:
    profiles: [microservices]
    build:
      context: ../../PhDAssess-ISA
    environment:
      - ZEEBE_ADDRESS=zeebe_node_0:29501
    env_file:
      - ../../PhDAssess-ISA/.env

volumes:
  es_data:
