app_name: "phd-assess"

# Config map
zeebe_config_map_name: "zeebe"

# Secrets
default_secrets_name: "all"
zeebe_secrets_name: "zeebe-broker"
meteor_secrets_name: "meteor-app"

# Images repository
quay_service_account_name: "rw-for-quay"
quay_host: "quay-its.epfl.ch"
quay_organisation_name: svc1394
quay_repo: "{{ quay_host }}/{{ quay_organisation_name }}"
_quay_push_pull_credential: "{{ lookup('file', '/keybase/team/epfl_phdassess/QUAY_BOT_ACCOUNT') }}"

quay_push_pull_config:
  auths:
    "quay-its.epfl.ch":
      "auth": "{{ _quay_push_pull_credential | b64encode }}"

# Zeebe
zeebe_gateway_service_name: "zeebe-gateway"

_zeebe_log_level: "info"

# The port of the “Zeebe gateways,” where clients connect with gRPC:
zeebe_gateway_network_port: 26500
zeebe_gateway_cluster_port: 26502
# The port through which gateways reach brokers. Note that despite
# every gateway having a broker next to it in the same pod, it will
# not necessarily talk to that one. (Rather, the network coordinates
# of all brokers are broadcast through the “gossip” mechanism when
# gateways start up)
zeebe_broker_network_command_api_port: 26501
# The port that brokers use to connect to each other to make the Raft network:
zeebe_broker_network_internal_api_port: 26502
zeebe_broker_network_monitoring_api_port: 9600

zeebe_route_name: "zeebe"

# Microservices
microservice_node_18_base_tag: "18-alpine"
microservice_node_18_base_image: "node:{{ microservice_node_18_base_tag }}"
microservice_node_22_base_tag: "22-alpine"
microservice_node_22_base_image: "node:{{ microservice_node_22_base_tag }}"

notifier_service_name: "notifier"
pdf_service_name: "pdf"

# Monitoring
monitoring_node_disk_usage_exporter_image: "{{ quay_repo }}/disk-usage-exporter"
zeebe_db_monitor_image: "{{ quay_repo }}/zeebe-db-monitor"
grafana_folder_name: "PhDAssess"
