app_name: "phd-assess"

# Secrets
default_secrets_name: "all"
meteor_secrets_name: "meteor-app"

# Images repository
quay_service_account_name: "rw-for-quay"
quay_host: "quay-its.epfl.ch"
quay_organisation_name: svc1394
quay_repo: "{{ quay_host }}/{{ quay_organisation_name }}"
_quay_push_pull_credential: "{{ lookup('file', '/keybase/team/epfl_phdassess/QUAY_BOT_ACCOUNT') }}"

quay_push_pull_config:
  auths:
    "quay-its.epfl.ch":
      "auth": "{{ _quay_push_pull_credential | b64encode }}"

# Zeebe
zeebe_gateway_service_name: "zeebe-gateway"

_zeebe_log_level: >-
  {{ "info" if is_test | default(false) else "info" }}

# The port of the “Zeebe gateways,” where clients connect with gRPC:
zeebe_gateway_network_port: 26500
zeebe_gateway_cluster_port: 26502
# The port through which gateways reach brokers. Note that despite
# every gateway having a broker next to it in the same pod, it will
# not necessarily talk to that one. (Rather, the network coordinates
# of all brokers are broadcast through the “gossip” mechanism when
# gateways start up)
zeebe_broker_network_commandApi_port: 26501
# The port that brokers use to connect to each other to make the Raft network:
zeebe_broker_network_internalApi_port: 26502
zeebe_broker_network_monitoringApi_port: 9600

zeebe_route_name: "zeebe"

zeebe_instance_env:
  PORT: '{{ zeebe_gateway_network_port }}'
  JAVA_OPTS: "{{ '-Xmx2024m' }}"
  ZEEBE_BROKER_NETWORK_MONITORINGAPI_HOST: '0.0.0.0'
  # https://docs.camunda.io/docs/self-managed/zeebe-deployment/operations/setting-up-a-cluster/
  ZEEBE_LOG_APPENDER: Stackdriver
  ZEEBE_BROKER_BACKPRESSURE_ALGORITHM: fixed
  ZEEBE_BROKER_BACKPRESSURE_FIXEDLIMIT_LIMIT: '300'
  ZEEBE_BROKER_THREADS_CPUTHREADCOUNT: '1'
  ZEEBE_BROKER_THREADS_IOTHREADCOUNT: '1'
  ZEEBE_BROKER_CLUSTER_CLUSTERNAME: epfl
  ZEEBE_BROKER_CLUSTER_CLUSTERSIZE: "3"
  ZEEBE_BROKER_CLUSTER_REPLICATIONFACTOR: "3"
  ZEEBE_LOG_LEVEL: "{{ _zeebe_log_level }}"
  ATOMIX_LOG_LEVEL: "{{ _zeebe_log_level }}"

# Microservices
microservice_node_18_base_tag: "18-alpine"
microservice_node_18_base_image: "node:{{ microservice_node_18_base_tag }}"
microservice_node_22_base_tag: "22-alpine"
microservice_node_22_base_image: "node:{{ microservice_node_22_base_tag }}"

notifier_service_name: "notifier"
pdf_service_name: "pdf"
