- name: Applying PodMonitor on Zeebe instances...
  kubernetes.core.k8s:
    definition:
      apiVersion: monitoring.coreos.com/v1
      kind: PodMonitor
      metadata:
        name: zeebe-monitoring
        namespace: '{{ openshift_namespace }}'
      spec:
        selector:
          matchLabels:
            app.kubernetes.io/name: 'zeebe'
        podMetricsEndpoints:
          - port: "metrics"
            path: '/actuator/prometheus'
            interval: '15s'

- name: Set Grafana folder...
  ansible.builtin.include_tasks:
    file: grafana.yml

- name: Set the Grafana dashboard config for Zeebe data...
  kubernetes.core.k8s:
    definition:
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: 'zeebe-grafana-dashboard'
        namespace: '{{ openshift_namespace }}'
      data:
        json: >
          {{ lookup('file', 'templates/grafana-dashboards/zeebe.json') | string }}

- name: Set the Grafana dashboard for Zeebe data...
  kubernetes.core.k8s:
    definition:
      apiVersion: grafana.integreatly.org/v1beta1
      kind: GrafanaDashboard
      metadata:
        name: 'zeebe'
        namespace: '{{ openshift_namespace }}'
      spec:
        resyncPeriod: 30s
        allowCrossNamespaceImport: true
        instanceSelector:
          matchLabels:
            dashboards: '{{ grafana_dashboard_instance }}'
        folder: "{{ grafana_folder_name }}"
        configMapRef:
          key: json
          name: 'zeebe-grafana-dashboard'
