- name: Applying Prometheus...
  ansible.builtin.include_tasks:
    file: monitoring/prometheus.yml
    apply:
      tags:
        - monitoring
        - monitoring.prometheus
  tags:
    - monitoring
    - monitoring.prometheus
    - monitoring.prometheus.restart

- name: Applying Disk usage monitor...
  ansible.builtin.include_tasks:
    file: monitoring/diskUsage.yml
    apply:
      tags:
        - monitoring
        - monitoring.disk-usage
  tags:
    - monitoring
    - monitoring.disk-usage

- name: Applying Zeebe DB monitor...
  ansible.builtin.include_tasks:
    file: monitoring/zeebeDbMonitor.yml
    apply:
      tags:
        - monitoring
        - monitoring.zeebe-db-monitor
  tags:
    - monitoring
    - monitoring.zeebe-db-monitor
