- name: "Applying one Zeebe StatefulSet"   # noqa name[template]
  vars:
    _instance_env:
      ZEEBE_BROKER_CLUSTER_NODEID: "{{ item.node_id }}"
      ZEEBE_BROKER_CLUSTER_INITIALCONTACTPOINTS: >-
        {{ ",".join(item.peers | default([])) }}
      # yamllint disable-line rule:line-length
      # https://github.com/camunda-cloud/zeebe/issues/5410 and
      # https://github.com/camunda-cloud/zeebe/blob/develop/qa/integration-tests/src/test/java/io/camunda/zeebe/it/network/AdvertisedAddressTest.java#L150
      ZEEBE_BROKER_NETWORK_INTERNALAPI_ADVERTISEDHOST: >-
        {{ item.quorum_name }}
      ZEEBE_BROKER_NETWORK_COMMANDAPI_ADVERTISEDHOST: >-
        {{ item.quorum_name }}
  kubernetes.core.k8s:
    definition:
      state: latest
      apiVersion: apps/v1
      kind: StatefulSet
      metadata:
        name: "{{ item.name }}"
        namespace: "{{ openshift_namespace }}"
        labels:
          app.kubernetes.io/name: "zeebe"
          app.kubernetes.io/component: "workflow-engine"
          app.kubernetes.io/part-of: "zeebe-quorum"
          app.kubernetes.io/managed-by: "ansible"
      spec:
        replicas: 1
        selector:
          matchLabels:
            app.kubernetes.io/instance: "{{ item.quorum_name }}"
            zeebe-quorum-member: "{{ item.quorum_name }}"
        podManagementPolicy: Parallel
        template:
          metadata:
            labels:
              for-service: "{{ zeebe_gateway_service_name }}"
              for-prometheus-job: zeebe
              zeebe-quorum-member: "{{ item.quorum_name }}"
              app.kubernetes.io/instance: "{{ item.quorum_name }}"
              app.kubernetes.io/version: "{{ zeebe_version }}"
          spec:
            serviceAccountName: "{{ quay_service_account_name }}"
            containers:
              - name: zeebe
                image:
                  "{{ zeebe_full_image_path_on_quay }}:{{ zeebe_version }}"
                env: >-
                  {{ zeebe_instance_env
                  | combine(_instance_env)
                  | combine(env | default({}))
                  | to_k8s_env }}
                resources:
                  requests:
                    cpu: '20m'
                    memory: '2000Mi'
                  limits:
                    cpu: '150m'
                    memory: '4000Mi'
                ports:
                  - name: metrics
                    containerPort: "{{ zeebe_broker_network_monitoringApi_port }}"
                volumeMounts:
                  - name: zeebe-data
                    mountPath: /usr/local/zeebe/data
                readinessProbe:
                  httpGet:
                    path: "/actuator/health/readiness"
                    scheme: "HTTP"
                    port: "{{ zeebe_broker_network_monitoringApi_port }}"
                  initialDelaySeconds: 60
                  periodSeconds: 30
                  successThreshold: 1
                  failureThreshold: 10
                  timeoutSeconds: 1
                livenessProbe:
                  httpGet:
                    path: "/actuator/health/liveness"
                    scheme: "HTTP"
                    port: "{{ zeebe_broker_network_monitoringApi_port }}"
                  initialDelaySeconds: 30
                  periodSeconds: 30
                  successThreshold: 1
                  failureThreshold: 5
                  timeoutSeconds: 1
            volumes:
              - name: zeebe-data
