- name: "Applying one PVC for a Zeebe instance"
  kubernetes.core.k8s:
    definition:
      apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: "{{ item.volume_claim_name }}"
        namespace: "{{ openshift_namespace }}"
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: thin-csi
        resources:
          requests:
            storage: 9Gi
