- name: One Zeebe StatefulSet   # noqa name[template]
  vars:
    _instance_env:
      ZEEBE_BROKER_CLUSTER_NODEID: "{{ item.node_id }}"
      ZEEBE_BROKER_CLUSTER_INITIALCONTACTPOINTS: >-
        {{ ",".join(item.peers | default([])) }}
      # yamllint disable-line rule:line-length
      # https://github.com/camunda-cloud/zeebe/issues/5410 and
      # https://github.com/camunda-cloud/zeebe/blob/develop/qa/integration-tests/src/test/java/io/camunda/zeebe/it/network/AdvertisedAddressTest.java#L150
      ZEEBE_BROKER_NETWORK_INTERNALAPI_ADVERTISEDHOST: >-
        {{ item.quorum_name }}
      ZEEBE_BROKER_NETWORK_COMMANDAPI_ADVERTISEDHOST: >-
        {{ item.quorum_name }}
    _zeebe_container:
      name: "zeebe"
      image: "{{ zeebe_quay_image_full_path }}"
      imagePullPolicy: Always
      env: >-
        {{ _instance_env | to_k8s_env }}
      envFrom:
        - configMapRef:
            name: "zeebe-broker"
        - secretRef:
            name: "{{ zeebe_secrets_name }}-s3"
      resources:
        requests:
          cpu: '15m'
          memory: '2000Mi'
        limits:
          memory: '4000Mi'
      ports:
        - name: metrics
          containerPort: "{{ zeebe_broker_network_monitoring_api_port }}"
      volumeMounts:
        - name: zeebe-data
          mountPath: /usr/local/zeebe/data
    _zeebe_monitor_container:
      name: "zeebe-db-monitor"
      image: "{{ zeebe_db_monitor_image }}:{{ zeebe_db_monitor_image_tag }}"
      imagePullPolicy: Always
      env:
        - name: 'ZEEBE_DB_MONITOR_SNAPSHOT_PATH'
          value: '/data/raft-partition/partitions/1/runtime'
        - name: 'ZEEBE_DB_MONITOR_SECONDARY_PATH'
          value: '/zeebe-db-monitor-secondary'
        - name: 'ZEEBE_DB_MONITOR_LDB_RESULTS_CACHE_TTL'
          value: '60000'
        - name: 'ZEEBE_DB_MONITOR_CMD_DEBUG'
          value: 'false'
        - name: 'ZEEBE_DB_MONITOR_DECODER_SHOW_WARNING_IN_CONSOLE'
          value: 'false'
      volumeMounts:
        - mountPath: /data/
          name: zeebe-data
          readOnly: true
        # the working path where you can find the symlinked zeebe data
        - mountPath: /zeebe-db-monitor-secondary
          name: volume-zeebe-db-monitor-secondary
      resources:
        requests:
          cpu: "5m"
          memory: "150Mi"
        limits:
          memory: "300Mi"
      ports:
        - name: db-metrics
          containerPort: 8081
    _instance_containers: >-
      {{ [_zeebe_monitor_container, _zeebe_container] if item.node_id == 0 else [_zeebe_container] }}
    _instance_volumes: |
      {% set vols = [{ 'name': 'zeebe-data', 'persistentVolumeClaim': { 'claimName': item.data_claim_name } }] %}
      {% if item.node_id == 0 %}
      {% set _ = vols.append({ 'name': 'volume-zeebe-db-monitor-secondary', 'emptyDir': {} }) %}
      {% endif %}
      {{ vols | to_json }}
  kubernetes.core.k8s:
    definition:
      state: latest
      apiVersion: apps/v1
      kind: StatefulSet
      metadata:
        name: "{{ item.name }}"
        namespace: "{{ openshift_namespace }}"
        labels:
          app.kubernetes.io/name: "zeebe"
          app.kubernetes.io/component: "backend"
          app.kubernetes.io/part-of: "zeebe-quorum"
      spec:
        replicas: 1
        selector:
          matchLabels:
            app.kubernetes.io/instance: "{{ item.quorum_name }}"
            zeebe-quorum-member: "{{ item.quorum_name }}"
        podManagementPolicy: Parallel
        template:
          metadata:
            annotations:
              kubectl.kubernetes.io/default-container: "zeebe"
            labels:
              for-service: "{{ zeebe_gateway_service_name }}"
              for-prometheus-job: zeebe
              zeebe-quorum-member: "{{ item.quorum_name }}"
              app.kubernetes.io/instance: "{{ item.quorum_name }}"
              app.kubernetes.io/version: "{{ zeebe_version }}"
              app.kubernetes.io/name: "zeebe"
          spec:
            serviceAccountName: "{{ quay_service_account_name }}"
            containers: "{{ _instance_containers }}"
            volumes: "{{ _instance_volumes }}"
            # Keep the pods spread into different physical nodes
            affinity:
              podAntiAffinity:
                requiredDuringSchedulingIgnoredDuringExecution:
                  - labelSelector:
                      matchLabels:
                        app.kubernetes.io/name: "zeebe"
                    topologyKey: "topology.kubernetes.io/zone"
