- name: Setting the Zeebe instances
  ansible.builtin.include_tasks: _instance.yml
  loop: "{{ zeebe_instance_config }}"
  vars:
    zeebe_instance_config:
      - node_id: 0
        name: "zeebe-0"
        quorum_name: "zeebe-quorum-0"
        data_volume:
          emptyDir: {}
        peers:
          - "zeebe-quorum-1:{{ zeebe_broker_network_internalApi_port }}"
          - "zeebe-quorum-2:{{ zeebe_broker_network_internalApi_port }}"
      - node_id: 1
        name: "zeebe-1"
        quorum_name: "zeebe-quorum-1"
        data_volume:
          emptyDir: {}
        peers:
          - "zeebe-quorum-0:{{ zeebe_broker_network_internalApi_port }}"
          - "zeebe-quorum-2:{{ zeebe_broker_network_internalApi_port }}"
      - node_id: 2
        name: "zeebe-2"
        quorum_name: "zeebe-quorum-2"
        data_volume:
          emptyDir: {}
        peers:
          - "zeebe-quorum-0:{{ zeebe_broker_network_internalApi_port }}"
          - "zeebe-quorum-1:{{ zeebe_broker_network_internalApi_port }}"

- name: Quorum Services
  kubernetes.core.k8s:
    definition:
      state: latest
      apiVersion: v1
      kind: Service
      metadata:
        name: "{{ item }}"
        namespace: "{{ openshift_namespace }}"
      spec:
        type: ClusterIP
        ports:
          - name: "zeebe-gateway"
            port: "{{ zeebe_gateway_network_port }}"
            protocol: TCP
            targetPort: "{{ zeebe_gateway_network_port }}"
          - name: "zeebe-broker-command-api"
            port: "{{ zeebe_broker_network_commandApi_port }}"
            protocol: TCP
            targetPort: "{{ zeebe_broker_network_commandApi_port }}"
          - name: "zeebe-broker-internal-api"
            port: "{{ zeebe_broker_network_internalApi_port }}"
            protocol: TCP
            targetPort: "{{ zeebe_broker_network_internalApi_port }}"
        selector:
          app.kubernetes.io/instance: "{{ item }}"
  loop:
    - "zeebe-quorum-0"
    - "zeebe-quorum-1"
    - "zeebe-quorum-2"
  tags: zeebe.service

- name: "Zeebe Gateway Service"
  kubernetes.core.k8s:
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: "{{ zeebe_gateway_service_name }}"
        namespace: "{{ openshift_namespace }}"
      spec:
        type: ClusterIP
        ports:
          - name: "zeebe-gateway-network"
            port: "{{ zeebe_gateway_network_port }}"
            protocol: TCP
            targetPort: "{{ zeebe_gateway_network_port }}"
        selector:
          for-service: "{{ zeebe_gateway_service_name }}"
