- name: "Zeebe Broker S3 secrets"
  kubernetes.core.k8s:
    definition:
      apiVersion: v1
      kind: Secret
      type: Opaque
      metadata:
        name: "{{ zeebe_secrets_name }}-s3"
        namespace: "{{ openshift_namespace }}"
      stringData:
        ZEEBE_BROKER_DATA_BACKUP_STORE: "S3"
        ZEEBE_BROKER_DATA_BACKUP_S3_REGION: "eu-central-2"
        ZEEBE_BROKER_DATA_BACKUP_S3_ENDPOINT: "https://s3.epfl.ch"
        ZEEBE_BROKER_DATA_BACKUP_S3_BUCKETNAME:
          "{{
            lookup(
              'file',
              keybase_secrets_folder + 'S3-zeebe-backup/ZEEBE_BROKER_DATA_BACKUP_S3_BUCKETNAME'
            )
          }}"
        ZEEBE_BROKER_DATA_BACKUP_S3_ACCESSKEY:
          "{{
            lookup(
              'file',
              keybase_secrets_folder + 'S3-zeebe-backup/ZEEBE_BROKER_DATA_BACKUP_S3_ACCESSKEY'
            )
          }}"
        ZEEBE_BROKER_DATA_BACKUP_S3_SECRETKEY:
          "{{
            lookup(
              'file',
              keybase_secrets_folder + 'S3-zeebe-backup/ZEEBE_BROKER_DATA_BACKUP_S3_SECRETKEY'
            )
          }}"
